import { describe,it,expect } from 'vitest';
import { Adventure, createContainer,tickFurnace,transfer,positionKey } from '../src/game/Adventure';
import { Inventory } from '../src/game/Inventory';
import { I } from '../src/game/items';
import { B } from '../src/world/blocks';
import { World } from '../src/world/World';
import { columnIndex } from '../src/world/constants';
import { Player } from '../src/game/Player';
import { MobManager } from '../src/game/Mobs';
import { buildVillages } from '../src/world/villages';
function setup(){const world=new World(),a=new Adventure(world);for(let cz=-1;cz<=1;cz++)for(let cx=-1;cx<=1;cx++){const b=new Uint8Array(32768);for(let z=0;z<16;z++)for(let x=0;x<16;x++)b[columnIndex(x,20,z)]=B.STONE;world.addColumn(cx,cz,b);}return {world,a};}
describe('survival workstations and storage',()=>{
 it('smelts over time, consumes fuel once, and resumes a saved batch',()=>{const c=createContainer('furnace');c.slots[0]={id:I.RAW_FISH,count:2};c.slots[1]={id:I.COAL,count:1};tickFurnace(c,2.5);expect(c.slots[2]).toBeNull();expect(c.slots[1]).toBeNull();const saved=JSON.parse(JSON.stringify(c));tickFurnace(saved,2.5);expect(saved.slots[2]).toEqual({id:I.COOKED_FISH,count:1});expect(saved.burn).toBeCloseTo(75);tickFurnace(saved,5);expect(saved.slots[2].count).toBe(2);expect(saved.slots[0]).toBeNull();});
 it('does not ignite when output is full or incompatible',()=>{const c=createContainer('furnace');c.slots=[{id:I.RAW_FISH,count:1},{id:I.COAL,count:1},{id:I.COOKED_FISH,count:64}];tickFurnace(c,10);expect(c.slots[1]?.count).toBe(1);expect(c.progress).toBe(0);c.slots[2]={id:I.IRON_INGOT,count:1};tickFurnace(c,10);expect(c.burn).toBe(0);});
 it('resets partial progress when input changes and cannot smelt without fuel',()=>{const c=createContainer('furnace');c.slots[0]={id:I.RAW_FISH,count:2};tickFurnace(c,6);expect(c.progress).toBe(0);c.slots[1]={id:I.STICK,count:2};tickFurnace(c,2);c.slots[0]={id:I.RAW_BEEF,count:1};tickFurnace(c,.1);expect(c.progress).toBeCloseTo(.1);});
 it('moves only what fits and preserves worn equipment',()=>{const from=[{id:I.COAL,count:12}],to=[{id:I.COAL,count:60}];expect(transfer(from,0,to)).toBe(4);expect(from[0].count).toBe(8);const worn=[{id:I.IRON_PICKAXE,count:1,dur:7}],bag=Array(18).fill(null);transfer(worn,0,bag);expect(bag[0].dur).toBe(7);});
 it('trades atomically when there is no room and swaps gear without deletion',()=>{const {a}=setup(),inv=new Inventory('survival');inv.slots=Array.from({length:36},()=>({id:B.STONE,count:64}));inv.slots[0]={id:I.WHEAT,count:8};const before=inv.serialize();expect(a.trade(inv,I.WHEAT,4,I.EMERALD,1)).toBe(false);expect(inv.serialize()).toEqual(before);inv.slots[1]={id:I.HELMET,count:1,dur:12};expect(a.equip(inv,1)).toBe(true);expect(a.protection).toBeCloseTo(.08);a.wearArmour();expect(a.data.equipment.head?.dur).toBe(11);expect(a.unequip(inv,'head')).toBe(true);expect(inv.slots[1]?.dur).toBe(11);});
 it('conserves all 59 possible stacks in a death backpack and supports keep inventory',()=>{const {a,world}=setup(),inv=new Inventory('survival');inv.slots=Array.from({length:36},()=>({id:I.IRON_PICKAXE,count:1,dur:9}));a.data.backpack=Array.from({length:18},()=>({id:I.BOW,count:1,dur:22}));for(const k of ['head','body','legs','feet','shield'] as const)a.data.equipment[k]={id:I.SHIELD,count:1,dur:8};expect(a.makeGrave(inv,4,21,4)).toBe(true);const g=a.data.grave!;expect(world.getBlock(g.x,g.y,g.z)).toBe(B.GRAVE);expect(a.container(g.x,g.y,g.z).slots.filter(Boolean)).toHaveLength(59);expect(inv.slots.every(s=>!s)).toBe(true);a.data.keepInventory=true;inv.add(I.DIAMOND,3);expect(a.makeGrave(inv,4,21,4)).toBe(false);expect(inv.count(I.DIAMOND)).toBe(3);});
 it('round-trips furnace, equipment, backpack and grave through old version save data',()=>{const {a,world}=setup();world.setBlock(3,21,3,B.FURNACE);const c=a.container(3,21,3);c.slots[0]={id:I.RAW_FISH,count:1};c.slots[1]={id:I.COAL,count:1};a.update(2,0,21,0,true);a.data.backpack[0]={id:I.BOW,count:1,dur:5};const raw=JSON.parse(JSON.stringify(a.data));a.reset(raw);expect(a.data.backpack[0]?.dur).toBe(5);expect(a.data.containers[positionKey(3,21,3)].progress).toBeCloseTo(2);});
});
describe('farming and useful block physics',()=>{
 it('runs workstation clocks in real time without enlarging physics steps',()=>{const {world,a}=setup();world.setBlock(4,21,4,B.FURNACE);const c=a.container(4,21,4);c.slots[0]={id:I.RAW_FISH,count:1};c.slots[1]={id:I.COAL,count:1};for(let i=0;i<10;i++)a.update(.1,0,21,0,true,.5);expect(c.slots[2]?.id).toBe(I.COOKED_FISH);expect(a.data.clock).toBeCloseTo(185);});
 it('requires irrigation and advances all crop stages over 72 seconds',()=>{const {a,world}=setup();world.setBlock(4,20,4,B.FARMLAND);world.setBlock(4,21,4,B.CROP_0);for(let i=0;i<30;i++)a.update(1,0,21,0,true);expect(world.getBlock(4,21,4)).toBe(B.CROP_0);world.setBlock(5,20,4,B.WATER);for(let i=0;i<72;i++)a.update(1,0,21,0,true);expect(world.getBlock(4,21,4)).toBe(B.CROP_3);});
 it('lands on the actual top of a bed and passes through an open door',()=>{const {world}=setup();world.setBlock(4,21,4,B.BED);const p=new Player(world);p.x=4.5;p.z=4.5;p.y=24;p.peakY=24;const idle={forward:0,strafe:0,jump:false,down:false,sprint:false};for(let i=0;i<120;i++)p.update(1/60,idle,false);expect(p.y).toBeCloseTo(21.55,2);world.setBlock(8,21,5,B.DOOR_OPEN);world.setBlock(8,22,5,B.DOOR_TOP_OPEN);p.x=8.5;p.z=7;p.y=21;p.yaw=0;for(let i=0;i<45;i++)p.update(1/60,{...idle,forward:1},false);expect(p.z).toBeLessThan(5);});
 it('climbs ladders and stops falling while sneaking',()=>{const {world}=setup(),p=new Player(world);for(let y=21;y<27;y++)world.setBlock(3,y,3,B.LADDER);p.x=p.z=3.5;p.y=21;for(let i=0;i<60;i++)p.update(1/60,{forward:0,strafe:0,jump:true,down:false,sprint:false},false);expect(p.y).toBeGreaterThan(23);const before=p.y;for(let i=0;i<30;i++)p.update(1/60,{forward:0,strafe:0,jump:false,down:false,sprint:false,sneak:true},false);expect(p.y).toBeCloseTo(before);});
 it('breeds only a fed adult pair and persists their baby/cooldown',()=>{const {world,a}=setup(),mobs=new MobManager(world);mobs.adventure=a;const m=mobs.spawn('cow',4,21,4),n=mobs.spawn('cow',5,21,4);expect(mobs.feed(m,I.WHEAT)).toBe(true);expect(mobs.feed(n,I.SEEDS)).toBe(false);mobs.feed(n,I.WHEAT);mobs.update(.01,4,4);expect(mobs.mobs.filter(m=>m.baby>0)).toHaveLength(1);expect(m.breedCooldown).toBeGreaterThan(170);expect(mobs.feed(m,I.WHEAT)).toBe(false);const save=mobs.serialize();mobs.clear();mobs.restore(save);mobs.update(.01,4,4);expect(mobs.mobs.filter(m=>m.baby>0)).toHaveLength(1);mobs.clear();});
 it('generates deterministic functional villages across independent chunks',()=>{let count=0;for(let cz=0;cz<12;cz++)for(let cx=0;cx<12;cx++){const first=new Uint8Array(32768),second=new Uint8Array(32768);buildVillages(first,cx,cz,1729,()=>65);buildVillages(second,cx,cz,1729,()=>65);expect(first.every((id,i)=>id===second[i])).toBe(true);count+=first.filter(id=>id===B.CHEST).length;}expect(count).toBeGreaterThanOrEqual(3);});
});
