const {chromium}=require('playwright');const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist']});
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(45000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
 const shot=async name=>{fs.mkdirSync('e2e/screenshots',{recursive:true});await page.screenshot({path:`e2e/screenshots/${name}.png`});console.log('RENDER_IMAGE '+name+' '+(await page.screenshot({type:'jpeg',quality:65})).toString('base64'));};
 await page.goto('http://127.0.0.1:5173/?safe');await page.waitForFunction(()=>window.__minemine?.state==='menu',null,{timeout:120000});
 const ids=await page.evaluate(async()=>{const {I}=await import('/src/game/items.ts'),{B}=await import('/src/world/blocks.ts'),{Inventory}=await import('/src/game/Inventory.ts');const g=window.__minemine;g.applySettings({...g.settings,renderDistance:3,resolutionScale:.5});g.input.forceLocked=true;g.mode='survival';g.inventory=new Inventory('survival');g.inventory.onChange(()=>g.onInventoryChange());g.inventory.add(I.RAW_FISH,2);g.inventory.add(I.COAL,3);g.inventory.add(I.BACKPACK,1);g.inventory.add(I.HELMET,1,19);g.inventory.add(I.APPLE,3);g.inventory.add(I.BOW,1);g.inventory.add(I.ARROW,8);g.inventory.add(I.SHIELD,1);g.inventory.add(I.WHEAT,8);g.inventory.changed();g.enterPlaying();return {I,B};});
 await page.evaluate(B=>{const g=window.__minemine;g.player.x=.5;g.player.y=61;g.player.z=28.5;g.player.yaw=0;g.player.pitch=-.3;g.world.setBlock(0,61,26,B.FURNACE);g.chunks.flushUrgent();},ids.B);
 await page.waitForFunction(B=>window.__minemine.target?.id===B.FURNACE,ids.B);
 await page.mouse.click(720,450,{button:'right'});await page.waitForFunction(()=>window.__minemine.adventureUI.open&&window.__minemine.adventureUI.kind==='furnace');
 await page.locator('[data-source="inventory"][data-slot="0"]').click();await page.locator('[data-source="inventory"][data-slot="1"]').click();
 await page.waitForFunction(()=>window.__minemine.adventureUI.container.progress>.3);await shot('adventure-furnace');
 await page.waitForFunction(()=>window.__minemine.adventureUI.container.slots[2]?.count>=1,null,{timeout:45000});await page.locator('[data-source="storage"][data-slot="2"]').click();assert.ok(await page.evaluate(id=>window.__minemine.inventory.count(id)>0,ids.I.COOKED_FISH));
 await page.getByRole('button',{name:'Close panel'}).click();await page.keyboard.press('KeyB');await page.waitForFunction(()=>window.__minemine.adventureUI.kind==='backpack'&&window.__minemine.adventureUI.open);await page.locator('[data-source="inventory"][data-slot="2"]').click();assert.equal(await page.evaluate(id=>window.__minemine.inventory.count(id),ids.I.BACKPACK),1);await page.locator('[data-source="inventory"][data-slot="3"]').click();assert.equal(await page.evaluate(()=>window.__minemine.adventure.data.backpack[0].dur),19);await page.locator('[data-source="storage"][data-slot="0"]').click();
 await page.getByRole('button',{name:'Equipment [O]',exact:true}).click();const helmetIndex=await page.evaluate(id=>window.__minemine.inventory.slots.findIndex(s=>s?.id===id),ids.I.HELMET);await page.locator(`[data-source="inventory"][data-slot="${helmetIndex}"]`).click();assert.equal(await page.evaluate(()=>window.__minemine.adventure.protection),.08);await shot('adventure-equipment');
 await page.getByRole('button',{name:'Journal [J]',exact:true}).click();await shot('adventure-journal');await page.getByRole('button',{name:'Close panel'}).click();
 await page.evaluate(id=>{const g=window.__minemine;g.food=10;g.inventory.select(g.inventory.slots.findIndex(s=>s?.id===id));g.player.pitch=.7;},ids.I.APPLE);
 await page.mouse.down({button:'right'});await page.waitForFunction(()=>window.__minemine.eating>.2);await shot('adventure-eating');await page.waitForFunction(()=>window.__minemine.food>10);await page.mouse.up({button:'right'});assert.equal(await page.evaluate(id=>window.__minemine.inventory.count(id),ids.I.APPLE),2);
 // Empty-hand punch and physical combat drops use the real input path.
 await page.evaluate(()=>{const g=window.__minemine;g.inventory.slots[8]=null;g.inventory.select(8);g.player.pitch=.8;});await page.mouse.down();await page.waitForFunction(()=>window.__minemine.renderer.held.swing>.2);await page.mouse.up();
 const combat=await page.evaluate(async ids=>{const g=window.__minemine;g.mobs.clear();g.player.x=.5;g.player.y=61;g.player.z=28.5;g.player.yaw=0;g.player.pitch=-.1;g.inventory.slots[5]={id:ids.I.BOW,count:1,dur:100};g.inventory.selected=5;g.inventory.changed();g.world.setBlock(0,61,26,ids.B.AIR);const cow=g.mobs.spawn('cow',.5,61,24.5);cow.health=10;cow.wanderTimer=99;cow.moving=false;return cow.health;},ids);assert.equal(combat,10);await page.mouse.down({button:'right'});await page.waitForFunction(()=>window.__minemine.bowCharge>1.05);await page.mouse.up({button:'right'});await page.waitForFunction(()=>window.__minemine.adventure.data.drops.some(d=>d.stack.id===283));
 const flags=await page.evaluate(ids=>{const g=window.__minemine;
  const a=g.mobs.spawn('cow',2,61,28),b=g.mobs.spawn('cow',3,61,28);g.mobs.feed(a,ids.I.WHEAT);g.mobs.feed(b,ids.I.WHEAT);g.mobs.update(2.1,g.player.x,g.player.z);
  g.adventure.data.equipment.shield={id:ids.I.SHIELD,count:1,dur:50};g.health=20;g.invulnerable=0;g.blocking=true;g.blockTime=.1;g.combatDamage(4,g.player.x,g.player.z-1);const parry=g.health===20;
  g.invulnerable=0;g.blocking=false;g.combatDamage(4,g.player.x,g.player.z-1);const armour=g.health>16;
  const v=g.adventure.nearestVillage(0,4);g.mobs.startRescue(v);const scout=g.mobs.mobs.find(m=>m.role==='scout');if(scout){g.adventure.data.rescue.following=true;scout.x=v.x+1;scout.z=v.z+1;g.mobs.update(.01,g.player.x,g.player.z);}
  return {baby:g.mobs.mobs.some(m=>m.baby>0),parry,armour,rescue:g.adventure.data.rescue?.complete};},ids);assert.deepEqual(flags,{baby:true,parry:true,armour:true,rescue:true});
 await page.evaluate(ids=>{const g=window.__minemine;g.adventure.data.keepInventory=false;g.inventory.add(ids.I.DIAMOND,2);g.die('Verification');},ids);await page.waitForFunction(()=>window.__minemine.state==='dead');assert.ok(await page.evaluate(()=>!!window.__minemine.adventure.data.grave));
 await page.evaluate(()=>{const g=window.__minemine;const p=g.adventure.data.grave;g.state='playing';g.ui.hideDeath();g.openAdventure('grave',p);});await shot('adventure-recovery');await page.getByRole('button',{name:'Take all',exact:true}).click();assert.equal(await page.evaluate(id=>window.__minemine.inventory.count(id),ids.I.DIAMOND),2);await page.getByRole('button',{name:'Close panel'}).click();
 await page.evaluate(ids=>{const g=window.__minemine;g.world.setBlock(3,61,27,ids.B.CHEST);g.adventure.container(3,61,27).slots[0]={id:ids.I.DIAMOND,count:7};g.save();},ids);
 await page.reload();await page.waitForFunction(()=>window.__minemine?.state==='menu',null,{timeout:120000});assert.equal(await page.evaluate(()=>window.__minemine.adventure.data.containers['3,61,27'].slots[0].count),7);
 await page.evaluate(()=>{const g=window.__minemine;g.input.forceLocked=true;g.enterPlaying();g.openAdventure('journal');});await page.setViewportSize({width:390,height:844});await shot('adventure-mobile');assert.ok(await page.evaluate(()=>document.querySelector('.adventure-panel').getBoundingClientRect().right<=innerWidth));
 assert.deepEqual(errors,[]);console.log('PASS: furnace, storage, equipment, journal, eating, punch, bow, breeding, parry, rescue, grave and reload');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
