const { chromium } = require('playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ args: ['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  fs.mkdirSync('e2e/screenshots', { recursive: true });
  const shot = async name => {
    await page.screenshot({ path: `e2e/screenshots/${name}.png` });
    console.log('RENDER_IMAGE '+name+' '+(await page.screenshot({ type: 'jpeg', quality: 65 })).toString('base64'));
  };
  await page.goto(process.env.URL || 'http://127.0.0.1:5173/?debug');
  await page.waitForFunction(() => window.__minemine?.state === 'menu', null, { timeout: 120000 });
  await shot('workshop-menu');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const fov = page.getByRole('slider', { name: 'Field of view', exact: true });
  await fov.focus(); await fov.press('ArrowRight'); await fov.press('Tab');
  await page.waitForFunction(() => window.__minemine.settings.fov > 70);
  await page.screenshot({ path: 'e2e/screenshots/workshop-settings.png' });
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.getByRole('button', { name: 'Controls', exact: true }).click();
  assert.ok(await page.locator('.controls').isVisible());
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('button', { name: 'Create a world' }).click();
  await page.getByLabel('World seed').fill('typed seed');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  assert.equal(await page.evaluate(() => window.__minemine.seedText), 'Hearthvale');
  await page.evaluate(() => window.__minemine.input.forceLocked = true);
  await page.click('#play-btn'); await page.waitForFunction(() => window.__minemine.state === 'playing');
  await page.keyboard.press('KeyE'); await page.locator('.inventory-panel').waitFor();
  await shot('workshop-creative');
  await page.locator('#item-search').fill('pickaxe');
  assert.equal(await page.locator('.catalog-grid .slot').count(), 4);
  await page.locator('#item-search').pressSequentially('ee12');
  assert.equal(await page.evaluate(() => window.__minemine.state), 'inventory', 'Typing does not close the inventory or switch slots');
  await page.locator('#item-search').fill('');
  await page.getByRole('button', { name: 'Tools', exact: true }).click();
  assert.equal(await page.locator('.catalog-grid .slot').count(), 16);
  await shot('workshop-tools');
  await page.getByRole('button', { name: 'Diamond Pickaxe', exact: true }).click({ modifiers: ['Shift'] });
  assert.ok(await page.evaluate(() => window.__minemine.inventory.slots.slice(0,9).some(s => s?.id === 272)));
  await page.getByRole('button', { name: 'Close inventory' }).click();
  await page.waitForFunction(() => window.__minemine.state === 'playing');
  // A survival fixture exercises the real workshop, inventory callbacks and actions.
  const ids = await page.evaluate(async () => {
    const { Inventory } = await import('/src/game/Inventory.ts');
    const { I } = await import('/src/game/items.ts');
    const { B } = await import('/src/world/blocks.ts');
    const g = window.__minemine; g.mode = 'survival'; g.inventory = new Inventory('survival');
    g.inventory.onChange(() => g.onInventoryChange());
    g.inventory.add(I.WOOD_PICKAXE,1,17); g.inventory.add(B.OAK_LOG,3);
    g.inventory.add(B.OAK_PLANKS,12); g.inventory.add(I.STICK,4); g.inventory.add(I.APPLE,5);
    g.inventory.changed(); g.openInventory(); g.ui.openInventory(g.inventory, new Set(['hand']));
    return { I, B };
  });
  await page.getByRole('button', { name: 'Crafting table', exact: false }).filter({ hasText: 'Requires station' }).click();
  assert.equal(await page.locator('#craft-one').isDisabled(), true);
  await page.getByRole('button', { name: 'By hand', exact: true }).click();
  await page.locator(`[data-recipe="${ids.B.OAK_PLANKS}"]`).click();
  await page.click('#craft-one');
  assert.equal(await page.evaluate(id => window.__minemine.inventory.count(id), ids.B.OAK_LOG), 2);
  await page.click('#craft-max');
  assert.equal(await page.evaluate(id => window.__minemine.inventory.count(id), ids.B.OAK_LOG), 0);
  assert.equal(await page.evaluate(id => window.__minemine.inventory.count(id), ids.B.OAK_PLANKS), 24);
  await page.evaluate(() => window.__minemine.ui.openInventory(window.__minemine.inventory, new Set(['hand','table','furnace'])));
  await page.locator('#recipe-search').fill('wooden pickaxe');
  await page.click('#craft-one');
  assert.equal(await page.evaluate(id => window.__minemine.inventory.count(id), ids.I.WOOD_PICKAXE), 2);
  await page.locator('#recipe-search').fill('');
  await page.locator(`[data-recipe="${ids.I.WOOD_PICKAXE}"]`).click();
  await shot('workshop-survival');
  // Cursor return must preserve the durability of a used tool.
  await page.locator('.inventory-hotbar [data-slot="0"]').click();
  assert.ok(await page.evaluate(() => { const g=window.__minemine; return g.inventory.serialize(g.ui.carriedStack).slots.some(s=>s[0]===260 && s[2]===17); }), 'Autosave includes the used tool on the cursor');
  await page.getByRole('button', { name: 'Close inventory' }).click();
  assert.ok(await page.evaluate(() => window.__minemine.inventory.slots.some(s => s?.id === 260 && s.dur === 17)));
  // Real canvas click in empty air drives the arm through a visible arc.
  await page.evaluate(() => { const g=window.__minemine; g.inventory.slots[8]=null; g.inventory.select(8); g.player.pitch=0.8; });
  await page.waitForTimeout(600);
  const idle = await page.evaluate(() => window.__minemine.renderer.held.holder.position.toArray());
  await page.mouse.click(720,450);
  await page.waitForFunction(() => window.__minemine.renderer.held.swing > .1 && window.__minemine.renderer.held.swing < .85);
  assert.equal(await page.evaluate(() => window.__minemine.renderer.held.arm.visible),true);
  const moving = await page.evaluate(() => window.__minemine.renderer.held.holder.position.toArray());
  assert.ok(Math.hypot(...moving.map((v,i)=>v-idle[i])) > .01, 'Empty hand follows the swing arc');
  await page.waitForTimeout(650); await shot('workshop-hand');
  await page.evaluate(id => { const g=window.__minemine; g.inventory.pick(id); g.player.pitch=-.12; }, ids.I.WOOD_PICKAXE);
  await page.waitForTimeout(500); await shot('workshop-tool');
  await page.keyboard.press('KeyE');
  await page.setViewportSize({width:390,height:844});
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.equal(await page.evaluate(() => { const p=document.querySelector('.inventory-panel'); return p.scrollWidth > p.clientWidth; }), false);
  await shot('workshop-small');
  // Focus trap wraps from the last action to the inventory close control.
  await page.locator('#craft-max').focus(); await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(() => document.activeElement.getAttribute('aria-label')), 'Close inventory');
  assert.equal(errors.length,0, errors.join('\n'));
  await browser.close();
  console.log('PASS: menu, settings, creative search/categories, typing isolation, station gates, craft/max, tool durability, empty hand swing, responsive inventory and focus trap');
})().catch(e => { console.error(e); process.exit(1); });
